In [1]:
# Import pandas library for data manipulation and analysis
import pandas as pd
import numpy as np

In [2]:
# Load daily activity data for March–April period, daily activity data for April–May period and sleep tracking dataset
march_april = pd.read_csv(r"C:\Users\vinut\OneDrive\Desktop\Bellabeat_Smart_Device_Analysis\Raw_Data\mturkfitbit_export_3.12.16-4.11.16\Fitabase Data 3.12.16-4.11.16\dailyActivity_merged.csv")

april_may = pd.read_csv(r"C:\Users\vinut\OneDrive\Desktop\Bellabeat_Smart_Device_Analysis\Raw_Data\mturkfitbit_export_4.12.16-5.12.16\Fitabase Data 4.12.16-5.12.16\dailyActivity_merged.csv")

sleep_data = pd.read_csv(r"C:\Users\vinut\OneDrive\Desktop\Bellabeat_Smart_Device_Analysis\Raw_Data\mturkfitbit_export_4.12.16-5.12.16\Fitabase Data 4.12.16-5.12.16\sleepDay_merged.csv")

In [3]:
march_april.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [4]:
april_may.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [5]:
sleep_data.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

In [6]:
# Check number of rows and columns in each dataset
march_april.shape

(457, 15)

In [7]:
april_may.shape

(940, 15)

In [8]:
sleep_data.shape

(413, 5)

In [9]:
# Combine both months of daily activity data into one dataframe
daily_activity = pd.concat([march_april, april_may])

In [10]:
# Remove duplicate rows to ensure clean data
daily_activity = daily_activity.drop_duplicates()

In [11]:
# Convert ActivityDate column to datetime format for time-based analysis
daily_activity["ActivityDate"] = pd.to_datetime(daily_activity["ActivityDate"])

In [12]:
daily_activity.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [13]:
# Create new column showing the day of the week
daily_activity["DayOfWeek"] = daily_activity["ActivityDate"].dt.day_name()

In [14]:
daily_activity.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,DayOfWeek
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819,Friday
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154,Saturday
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944,Sunday
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932,Monday
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886,Tuesday

In [15]:
# Create new column showing the month name
daily_activity["Month"] = daily_activity["ActivityDate"].dt.month_name()

In [16]:
# Display first 5 rows
daily_activity.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,DayOfWeek,Month
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819,Friday,March
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154,Saturday,March
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944,Sunday,March
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932,Monday,March
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886,Tuesday,March

In [17]:
# Check column info and data types
daily_activity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1397 entries, 0 to 939
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        1397 non-null   int64
 1   ActivityDate              1397 non-null   datetime64[ns]
 2   TotalSteps                1397 non-null   int64
 3   TotalDistance             1397 non-null   float64
 4   TrackerDistance           1397 non-null   float64
 5   LoggedActivitiesDistance  1397 non-null   float64
 6   VeryActiveDistance        1397 non-null   float64
 7   ModeratelyActiveDistance  1397 non-null   float64
 8   LightActiveDistance       1397 non-null   float64
 9   SedentaryActiveDistance   1397 non-null   float64
 10  VeryActiveMinutes         1397 non-null   int64
 11  FairlyActiveMinutes       1397 non-null   int64
 12  LightlyActiveMinutes      1397 non-null   int64
 13  SedentaryMinutes          1397 non-null   int64
 14  Calories                  1397 non-null   int64
 15  DayOfWeek                 1397 non-null   object
 16  Month                     1397 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(7), object(2)
memory usage: 196.5+ KB

In [18]:
# Statistical summary of numeric columns
daily_activity.describe()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,1.397000e+03,1397,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000,1397.000000
mean,4.781210e+09,2016-04-19 01:26:35.132426496,7280.898354,5.219434,5.192219,0.131481,1.397416,0.538461,3.193407,0.001704,19.679313,13.403006,185.372942,992.542591,2266.265569
min,1.503960e+09,2016-03-12 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,2016-04-09 00:00:00,3146.000000,2.170000,2.160000,0.000000,0.000000,0.000000,1.610000,0.000000,0.000000,0.000000,111.000000,729.000000,1799.000000
50%,4.445115e+09,2016-04-19 00:00:00,6999.000000,4.950000,4.950000,0.000000,0.100000,0.200000,3.240000,0.000000,2.000000,6.000000,195.000000,1057.000000,2114.000000
75%,6.962181e+09,2016-04-30 00:00:00,10544.000000,7.500000,7.480000,0.000000,1.830000,0.770000,4.690000,0.000000,30.000000,18.000000,262.000000,1244.000000,2770.000000
max,8.877689e+09,2016-05-12 00:00:00,36019.000000,28.030001,28.030001,6.727057,21.920000,6.480000,12.510000,0.110000,210.000000,660.000000,720.000000,1440.000000,4900.000000
std,2.384293e+09,NaN,5214.336113,3.994206,3.980077,0.703683,2.607480,0.867436,2.116869,0.007736,31.675878,26.401247,114.058601,313.297376,753.005527

In [19]:
# Count missing values per column
daily_activity.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
DayOfWeek                   0
Month                       0
dtype: int64

In [20]:
# Count unique users in dataset
daily_activity["Id"].nunique()

35

In [21]:
# Count number of records per user
daily_activity["Id"].value_counts()

Id
4020332650    63
1503960366    50
1624580081    50
4702921684    46
4445114986    46
6962181067    45
2022484408    43
4319703577    43
8378563200    43
7086361926    43
2026352035    43
4558609924    43
1844505072    43
5553957443    43
8877689391    43
1927972279    43
2320127002    43
2873212765    43
8053475328    42
3977333714    42
8792009665    41
5577150313    41
1644430081    40
4388161847    39
8583815059    39
6290855005    39
6117666160    38
7007744171    38
4057192912    36
6775888955    35
2347167796    33
8253242879    31
3372868164    30
6391747486     9
2891001357     8
Name: count, dtype: int64

In [22]:
# Count number of user-day observations with zero recorded steps
zero_step_count = (daily_activity["TotalSteps"] == 0).sum()
zero_step_count

138

In [23]:
# Calculate percentage of zero-step user-day records
zero_step_percentage = (zero_step_count / len(daily_activity)) * 100
zero_step_percentage

9.87831066571224

In [24]:
# Count zero-step records per user
zero_steps_per_user = daily_activity[daily_activity["TotalSteps"] == 0]["Id"].value_counts()

zero_steps_per_user

Id
4020332650    14
1927972279    14
4057192912    14
1844505072    13
6290855005    13
6775888955    10
8792009665    10
4388161847     8
6117666160     7
8253242879     7
2891001357     6
6391747486     6
2320127002     4
4702921684     2
5577150313     2
7007744171     2
4319703577     1
1503960366     1
2873212765     1
2347167796     1
7086361926     1
8583815059     1
Name: count, dtype: int64

In [25]:
# Calculate total days per user
total_days_per_user = daily_activity["Id"].value_counts()

# Combine with zero-step counts
zero_analysis = pd.DataFrame({
    "TotalDays": total_days_per_user,
    "ZeroStepDays": zero_steps_per_user
}).fillna(0)

# Calculate percentage
zero_analysis["ZeroStepPercentage"] = (
    zero_analysis["ZeroStepDays"] / zero_analysis["TotalDays"]
) * 100

zero_analysis.sort_values("ZeroStepPercentage", ascending=False)

            TotalDays  ZeroStepDays  ZeroStepPercentage
Id
2891001357          8           6.0           75.000000
6391747486          9           6.0           66.666667
4057192912         36          14.0           38.888889
6290855005         39          13.0           33.333333
1927972279         43          14.0           32.558140
1844505072         43          13.0           30.232558
6775888955         35          10.0           28.571429
8792009665         41          10.0           24.390244
8253242879         31           7.0           22.580645
4020332650         63          14.0           22.222222
4388161847         39           8.0           20.512821
6117666160         38           7.0           18.421053
2320127002         43           4.0            9.302326
7007744171         38           2.0            5.263158
5577150313         41           2.0            4.878049
4702921684         46           2.0            4.347826
2347167796         33           1.0            3.030303
8583815059         39           1.0            2.564103
2873212765         43           1.0            2.325581
4319703577         43           1.0            2.325581
7086361926         43           1.0            2.325581
1503960366         50           1.0            2.000000
6962181067         45           0.0            0.000000
8378563200         43           0.0            0.000000
8053475328         42           0.0            0.000000
4445114986         46           0.0            0.000000
5553957443         43           0.0            0.000000
4558609924         43           0.0            0.000000
1624580081         50           0.0            0.000000
3977333714         42           0.0            0.000000
3372868164         30           0.0            0.000000
2026352035         43           0.0            0.000000
2022484408         43           0.0            0.000000
1644430081         40           0.0            0.000000
8877689391         43           0.0            0.000000

In [26]:
# Check zero-step days by weekday
daily_activity[daily_activity["TotalSteps"] == 0]["DayOfWeek"].value_counts()

DayOfWeek
Tuesday      27
Sunday       22
Saturday     21
Thursday     20
Monday       19
Friday       15
Wednesday    14
Name: count, dtype: int64

In [27]:
# Correlation matrix
daily_activity[["TotalSteps", "Calories", "VeryActiveMinutes"]].corr()

                   TotalSteps  Calories  VeryActiveMinutes
TotalSteps           1.000000  0.590160           0.676558
Calories             0.590160  1.000000           0.582028
VeryActiveMinutes    0.676558  0.582028           1.000000

In [28]:
# Remove users with less than 30 total recorded days
reliable_users = zero_analysis[zero_analysis["TotalDays"] >= 30]

# Remove users with more than 40% zero-step days
reliable_users = reliable_users[reliable_users["ZeroStepPercentage"] <= 40]

# Keep only reliable users in dataset
daily_activity_cleaned = daily_activity[
    daily_activity["Id"].isin(reliable_users.index)
]

In [29]:
daily_activity_cleaned["Id"].nunique()

33

In [30]:
daily_activity_cleaned.columns

Index(['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance',
       'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories', 'DayOfWeek',
       'Month'],
      dtype='object')

In [31]:
daily_activity_cleaned = daily_activity_cleaned.copy()

In [32]:
# Create activity level categories
def categorize_steps(steps):
    if steps < 5000:
        return "Sedentary"
    elif steps < 10000:
        return "Moderately Active"
    else:
        return "Active"

daily_activity_cleaned["ActivityLevel"] = (
    daily_activity_cleaned["TotalSteps"].apply(categorize_steps)
)

In [33]:
daily_activity_cleaned["ActivityLevel"].value_counts()

ActivityLevel
Sedentary            484
Moderately Active    466
Active               430
Name: count, dtype: int64

In [34]:
activity_percentage = (
    daily_activity_cleaned["ActivityLevel"].value_counts(normalize=True)
) * 100

activity_percentage

ActivityLevel
Sedentary            35.072464
Moderately Active    33.768116
Active               31.159420
Name: proportion, dtype: float64

In [35]:
# Calculate average steps per user
user_avg_steps = (
    daily_activity_cleaned
    .groupby("Id")["TotalSteps"]
    .mean()
)

# Categorize users by average steps
def categorize_avg_steps(steps):
    if steps < 5000:
        return "Sedentary User"
    elif steps < 10000:
        return "Moderately Active User"
    else:
        return "Highly Active User"

user_segments = user_avg_steps.apply(categorize_avg_steps)

user_segments.value_counts()

TotalSteps
Moderately Active User    15
Sedentary User            11
Highly Active User         7
Name: count, dtype: int64

In [36]:
# Check final dataset size after cleaning
print("Original number of records:", len(daily_activity))
print("Cleaned number of records:", len(daily_activity_cleaned))

# Calculate percentage of data retained
retained_percentage = (len(daily_activity_cleaned) / len(daily_activity)) * 100
print("Percentage of data retained:", round(retained_percentage, 2), "%")

# Check number of remaining users
print("Remaining unique users:", daily_activity_cleaned["Id"].nunique())

Original number of records: 1397
Cleaned number of records: 1380
Percentage of data retained: 98.78 %
Remaining unique users: 33

In [37]:
# Check which users were removed
original_users = set(daily_activity["Id"].unique())
cleaned_users = set(daily_activity_cleaned["Id"].unique())

removed_users = original_users - cleaned_users
removed_users

{2891001357, 6391747486}

In [38]:
zero_analysis.loc[[2891001357, 6391747486]]

            TotalDays  ZeroStepDays  ZeroStepPercentage
Id
2891001357          8           6.0           75.000000
6391747486          9           6.0           66.666667

In [39]:
# Calculate average calories per user
user_avg_calories = (
    daily_activity_cleaned
    .groupby("Id")["Calories"]
    .mean()
)

In [40]:
# Combine user segment and average calories into one dataframe
user_summary = pd.DataFrame({
    "UserSegment": user_segments,
    "AvgCalories": user_avg_calories
})

# View first few rows
user_summary.head()

                       UserSegment  AvgCalories
Id
1503960366      Highly Active User  1808.740000
1624580081  Moderately Active User  1433.780000
1644430081  Moderately Active User  2837.575000
1844505072          Sedentary User  1585.325581
1927972279          Sedentary User  2195.465116

In [41]:
# Calculate average calories for each user segment
segment_calorie_analysis = (
    user_summary
    .groupby("UserSegment")["AvgCalories"]
    .mean()
    .sort_values(ascending=False)
)

segment_calorie_analysis

UserSegment
Highly Active User        2390.886762
Moderately Active User    2384.702615
Sedentary User            2016.185391
Name: AvgCalories, dtype: float64

In [42]:
daily_activity_cleaned[["TotalSteps", "Calories"]].corr()

            TotalSteps  Calories
TotalSteps    1.000000  0.594629
Calories      0.594629  1.000000

In [43]:
# We are checking how strongly intense activity (VeryActiveMinutes) is related to calorie expenditure
daily_activity_cleaned[["VeryActiveMinutes", "Calories"]].corr()

                   VeryActiveMinutes  Calories
VeryActiveMinutes           1.000000  0.585606
Calories                    0.585606  1.000000

In [44]:
# Normalize TotalSteps using Min-Max scaling
daily_activity_cleaned["Steps_Normalized"] = (
    (daily_activity_cleaned["TotalSteps"] - daily_activity_cleaned["TotalSteps"].min())
    /
    (daily_activity_cleaned["TotalSteps"].max() - daily_activity_cleaned["TotalSteps"].min())
)

# Normalize VeryActiveMinutes using Min-Max scaling
daily_activity_cleaned["VeryActive_Normalized"] = (
    (daily_activity_cleaned["VeryActiveMinutes"] - daily_activity_cleaned["VeryActiveMinutes"].min())
    /
    (daily_activity_cleaned["VeryActiveMinutes"].max() - daily_activity_cleaned["VeryActiveMinutes"].min())
)

In [45]:
# Create composite activity score
# We give equal weight to Steps and Very Active Minutes
daily_activity_cleaned["ActivityScore"] = (
    0.5 * daily_activity_cleaned["Steps_Normalized"] +
    0.5 * daily_activity_cleaned["VeryActive_Normalized"]
)

# Check first few rows
daily_activity_cleaned[["TotalSteps", "VeryActiveMinutes",
                        "Steps_Normalized", "VeryActive_Normalized",
                        "ActivityScore"]].head()

,TotalSteps,VeryActiveMinutes,Steps_Normalized,VeryActive_Normalized,ActivityScore
0,11004,33,0.305505,0.157143,0.231324
1,17609,89,0.488881,0.423810,0.456345
2,12736,56,0.353591,0.266667,0.310129
3,13231,39,0.367334,0.185714,0.276524
4,12041,28,0.334296,0.133333,0.233815

In [46]:
# Calculate average ActivityScore per user
user_avg_activity_score = (
    daily_activity_cleaned
    .groupby("Id")["ActivityScore"]
    .mean()
)

# View first few users
user_avg_activity_score.head()

Id
1503960366    0.255259
1624580081    0.085205
1644430081    0.133904
1844505072    0.040644
1927972279    0.019887
Name: ActivityScore, dtype: float64

In [47]:
# Calculate percentile thresholds
low_threshold = user_avg_activity_score.quantile(0.33)
high_threshold = user_avg_activity_score.quantile(0.66)

# Define segmentation function
def categorize_activity_score(score):
    if score <= low_threshold:
        return "Low Activity User"
    elif score <= high_threshold:
        return "Moderate Activity User"
    else:
        return "High Activity User"

# Apply segmentation
composite_user_segments = user_avg_activity_score.apply(categorize_activity_score)

# Count users in each segment
composite_user_segments.value_counts()

ActivityScore
High Activity User        11
Low Activity User         11
Moderate Activity User    11
Name: count, dtype: int64

In [48]:
# Combine both segmentations into one dataframe
comparison_df = pd.DataFrame({
    "StepBasedSegment": user_segments,
    "CompositeSegment": composite_user_segments
})

# Create comparison table
segment_comparison = pd.crosstab(
    comparison_df["StepBasedSegment"],
    comparison_df["CompositeSegment"]
)

segment_comparison

CompositeSegment,High Activity User,Low Activity User,Moderate Activity User
StepBasedSegment,,,
Highly Active User,7,0,0
Moderately Active User,4,1,10
Sedentary User,0,10,1

In [49]:
# Combine composite segmentation with average calories per user
composite_summary = pd.DataFrame({
    "CompositeSegment": composite_user_segments,
    "AvgCalories": user_avg_calories
})

# Calculate average calories by composite segment
composite_calorie_analysis = (
    composite_summary
    .groupby("CompositeSegment")["AvgCalories"]
    .mean()
    .sort_values(ascending=False)
)

composite_calorie_analysis

CompositeSegment
High Activity User        2527.909788
Moderate Activity User    2266.195675
Low Activity User         1995.420523
Name: AvgCalories, dtype: float64

In [50]:
# Export cleaned dataset to CSV
daily_activity_cleaned.to_csv(
    r"C:\Users\vinut\OneDrive\Desktop\Bellabeat_Smart_Device_Analysis\bellabeat_cleaned_activity.csv",
    index=False
)

In [51]:
daily_activity_cleaned

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,...,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,DayOfWeek,Month,ActivityLevel,Steps_Normalized,VeryActive_Normalized,ActivityScore
0,1503960366,2016-03-25,11004,7.110000,7.110000,0.0,2.57,0.46,4.07,0.00,...,12,205,804,1819,Friday,March,Active,0.305505,0.157143,0.231324
1,1503960366,2016-03-26,17609,11.550000,11.550000,0.0,6.92,0.73,3.91,0.00,...,17,274,588,2154,Saturday,March,Active,0.488881,0.423810,0.456345
2,1503960366,2016-03-27,12736,8.530000,8.530000,0.0,4.66,0.16,3.71,0.00,...,5,268,605,1944,Sunday,March,Active,0.353591,0.266667,0.310129
3,1503960366,2016-03-28,13231,8.930000,8.930000,0.0,3.19,0.79,4.95,0.00,...,20,224,1080,1932,Monday,March,Active,0.367334,0.185714,0.276524
4,1503960366,2016-03-29,12041,7.850000,7.850000,0.0,2.16,1.09,4.61,0.00,...,28,243,763,1886,Tuesday,March,Active,0.334296,0.133333,0.233815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,2016-05-08,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,...,4,245,1174,2847,Sunday,May,Active,0.296677,0.080952,0.188815
936,8877689391,2016-05-09,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,...,19,217,1131,3710,Monday,May,Active,0.561537,0.347619,0.454578
937,8877689391,2016-05-10,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,...,11,224,1187,2832,Tuesday,May,Active,0.297982,0.085714,0.191848
938,8877689391,2016-05-11,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,...,12,213,1127,3832,Wednesday,May,Active,0.594686,0.419048,0.506867
939,8877689391,2016-05-12,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,...,1,137,770,1849,Thursday,May,Moderately Active,0.223882,0.109524,0.166703